version: '3.8'
services:
  issue-tracker:
    build: 
      args:
        - NODE_ENV=prod
      context: .
      dockerfile: Dockerfile
    image: 'it-prod'
    ports:
      - 3000:3000
    container_name: 'IT-PROD'
    env_file:
      - .env
