FROM node:22.1.0

WORKDIR /next

COPY package* .
COPY /prisma .

RUN npm install
RUN npx prisma generate
RUN npx prisma migrate dev

COPY . .

RUN ./next/npm build

EXPOSE 500

CMD ["./next/npm", "start"]