version: '3.8'
services:
  issue-tracker-dev:
    build: .
    image: 'node:22.1'
    args:
      - NODE_ENV=dev
    ports:
      - 3000:3000
    container_name: 'IT-DEV'
    volumes:
      - ./app:/next/app
    env_file:
      - .env

  issue-tracker-prod:
    build: .
    image: 'node:22.1'
    args:
      - NODE_ENV=prod
    ports:
      - 3000:5000
    container_name: 'IT-PROD'
    env_file:
      - .env
